version: '2'
services:
    nginxdocker-app:
        image: nginxdocker
        external_links:
            - nginxdocker-mysql:mysql
            - nginxdocker-elasticsearch:elasticsearch
            - nginxdocker-nginx:nginx
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/nginxdocker?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    nginxdocker-mysql:
        extends:
            file: mysql.yml
            service: nginxdocker-mysql
    nginxdocker-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: nginxdocker-elasticsearch
    nginxdocker-nginx:
        extends:
            file: nginx.yml
            service: nginxdocker-nginx
