version: '2'
services:
    nginxdocker-nginx:
        container_name: nginxdocker-nginx
        build: ./nginx/
        volumes:
            - ~/volumes/jhipster/NginxDocker/log/:/var/log/nginx/
        ports:
            - 80:80
            - 443:443
